INSERT INTO "Pickem_team" VALUES(0,'BAL','Baltimore','Ravens',0,0);
INSERT INTO "Pickem_team" VALUES(1,'CIN','Cincinnati','Bengals',0,0);
INSERT INTO "Pickem_team" VALUES(2,'CLE','Cleveland','Browns',0,0);
INSERT INTO "Pickem_team" VALUES(3,'PIT','Pittsburgh','Steelers',0,0);
INSERT INTO "Pickem_team" VALUES(4,'CHI','Chicago','Bears',0,0);
INSERT INTO "Pickem_team" VALUES(5,'DET','Detroit','Lions',0,0);
INSERT INTO "Pickem_team" VALUES(6,'GB','Green Bay','Packers',0,0);
INSERT INTO "Pickem_team" VALUES(7,'MIN','Minnesota','Vikings',0,0);
INSERT INTO "Pickem_team" VALUES(8,'HOU','Houston','Texans',0,0);
INSERT INTO "Pickem_team" VALUES(9,'IND','Indianapolis','Colts',0,0);
INSERT INTO "Pickem_team" VALUES(10,'JAX','Jacksonville','Jaguars',0,0);
INSERT INTO "Pickem_team" VALUES(11,'TEN','Tennesse','Titans',0,0);
INSERT INTO "Pickem_team" VALUES(12,'ATL','Atlanta','Falcons',0,0);
INSERT INTO "Pickem_team" VALUES(13,'CAR','Carolina','Panthers',0,0);
INSERT INTO "Pickem_team" VALUES(14,'NO','New Orleans','Saints',0,0);
INSERT INTO "Pickem_team" VALUES(15,'TB','Tampa Bay','Buccaneers',0,0);
INSERT INTO "Pickem_team" VALUES(16,'BUF','Buffalo','Bills',0,0);
INSERT INTO "Pickem_team" VALUES(17,'MIA','Miami','Dolphins',0,0);
INSERT INTO "Pickem_team" VALUES(18,'NE','New England','Patriots',0,0);
INSERT INTO "Pickem_team" VALUES(19,'NYJ','New York','Jets',0,0);
INSERT INTO "Pickem_team" VALUES(20,'DAL','Dallas','Cowboys',0,0);
INSERT INTO "Pickem_team" VALUES(21,'NYG','New York','Giants',0,0);
INSERT INTO "Pickem_team" VALUES(22,'PHI','Philidelphia','Eagles',0,0);
INSERT INTO "Pickem_team" VALUES(23,'WAS','Washington','Redskins',0,0);
INSERT INTO "Pickem_team" VALUES(24,'DEN','Denver','Broncos',0,0);
INSERT INTO "Pickem_team" VALUES(25,'KC','Kansas City','Chiefs',0,0);
INSERT INTO "Pickem_team" VALUES(26,'OAK','Oakland','Raiders',0,0);
INSERT INTO "Pickem_team" VALUES(27,'SD','San Diego','Chargers',0,0);
INSERT INTO "Pickem_team" VALUES(28,'ARZ','Arizona','Cardinals',0,0);
INSERT INTO "Pickem_team" VALUES(29,'SF','San Francisco','49ers',0,0);
INSERT INTO "Pickem_team" VALUES(30,'SEA','Seattle','Seahawks',0,0);
INSERT INTO "Pickem_team" VALUES(31,'STL','St. Louis','Rams',0,0);
